# Generated by Django 2.2.16 on 2023-05-18 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230518_0751'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlackListedToken',
        ),
    ]
